[package]
name = "wasm-life-emulation-demo"
version = "0.1.0"
authors = ["DeathMachine97 <mukhtarabeshov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"
typename = "0.1.1"
